
services:
  backend:
    build: ./backend/metrics
    ports:
      - "6001:6001"
    container_name: dashboard-backend

  frontend:
    build: ./frontend
    ports:
      - "5500:5500"
    container_name: dashboard-frontend
    depends_on:
      - backend
